services:
  - type: web
    name: agentic-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.11
    plan: free
    envVars:
      - key: SECRET_API_KEY
        sync: false  # You’ll still set it in the Render Dashboard